### ISSUE TITLE
聚类Minst数据集的问题

### ISSUE THREAD

**Issue by summersnowfish** [thupchnsky/query_kmeans#1]
Hi, thank you very much for your excellent work.
I have a question to ask. If I use your Noiseless Kmeans method for clustering the MNIST handwritten digit recognition dataset. The feature dimension of the data will be 784. In this case, the center points of the clusters are all 0. Why is this?

**Comment by thupchnsky** [comment]
Could you please elaborate on what "centers" you are referring to? Do you mean the real centers returned by sklearn Kmeans or the query Kmeans?

**Comment by summersnowfish** [comment]
@thupchnsky 
Sorry, my description just now was wrong.
When I use the query Kmeans method to cluster the Mnist dataset, since the size of the picture is 28*28, its feature dimension is 784. When I cluster them (I set --k=10 --d=784 ), will generate 7840 cluster centers, and many of these cluster centers are 0. But what I really want to get is 10 cluster centers. How can I do it? (I am referring to the real centers obtained by query Kmeans)

**Comment by thupchnsky** [comment]
What is the size of your returned `query_centers`? It should be an array of size k * d, and in this case, it should be 10*784 instead of an array of size 7840.

**Comment by summersnowfish** [comment]
The size of returned query_centers is 10*784. But in this case, I don't seem to be able to specifically know which number a certain picture in the clustered Minst dataset belongs to. 
Sorry I'm a newbie and can't figure it out here. If it is convenient, can you guide me how to get the accuracy of its clustering?

**Comment by thupchnsky** [comment]
First, since there are 10 clusters here, each row of `query_centers` is the center for one of the 10 clusters, and the centers have the same dimension as the original data, which is of size 784. Also, mnist is an image dataset, only a few positions of those 784 dimensions will be nonzero. That is maybe why you find there are many 0 in the `query_centers` array. Please refer to the description of mnist dataset for more details here.

Second, for k-means clustering, if you want to find out which cluster one specific sample belongs to, you just need to find its closest cluster center, and the sample belongs to the cluster indicated by that cluster center.

Third, for k-means clustering the objective is defined by a sum of L2 distances, instead of accuracy. That is why we only give the results about the objective function. I know the mnist dataset comes with labels, and normally one would use the given labels to compute the accuracy. However, in k-means setting the **true** labels would be different from the given labels in the dataset, and that is what line 38-39 in `noiseless` is for. If you really want to compute the accuracy the clustering result, you may want to use some metrics like "Normalized Mutual Information" [1, 2] that computes the agreement of the assigned clusters to the given labels, up to permutation.

[1] Z. F. Knops, J. A. Maintz, M. A. Viergever, and J. P. Pluim. Normalized mutual information based registration using k-means clustering and shading correction. Medical image analysis, 10(3):432–439, 2006.

[2] N. X. Vinh, J. Epps, and J. Bailey. Information theoretic measures for clusterings comparison: Variants, properties, normalization and correction for chance. Journal of Machine Learning Research, 11(Oct):2837–2854, 2010.

**Comment by summersnowfish** [comment]
Thanks a lot for your answer. I wish you good health and success in your studies in 2023.
thank you again

**Comment by thupchnsky** [comment]
Best wishes to you as well! I will then close this issue.
